spring:
  application:
    name: delivery-project

  # DB 연결
  datasource:
    url: jdbc:postgresql://localhost:5433/delivery
    username: delivery
    password: delivery1234

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true