spring:
  application:
    name: delivery-project

  # DB 연결
  datasource:
    url: jdbc:postgresql://localhost:5433/delivery
    username: delivery
    password: delivery1234

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080


jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==